/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-error': '#ffffff',
        'on-secondary-fixed': '#00201e',
        'outline-variant': '#bccac2',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-background': '#171d1a',
        'surface-container-low': '#eff5f0',
        'surface-bright': '#f4fbf6',
        'tertiary-fixed-dim': '#44deb7',
        background: '#f4fbf6',
        'on-primary-container': '#00765b',
        'primary-fixed': '#79f9ce',
        'tertiary-container': '#7bffd9',
        'inverse-surface': '#2b322f',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#5adcb3',
        surface: '#f4fbf6',
        'inverse-on-surface': '#ecf2ed',
        primary: '#006c52',
        'on-error-container': '#93000a',
        'on-surface-variant': '#3d4a44',
        'on-tertiary-fixed-variant': '#005140',
        'surface-tint': '#006c52',
        'surface-container-highest': '#dde4df',
        error: '#ba1a1a',
        'surface-container-high': '#e3eae5',
        'on-tertiary-fixed': '#002018',
        'error-container': '#ffdad6',
        'on-secondary-container': '#006f69',
        'primary-container': '#7fffd4',
        secondary: '#006a64',
        'tertiary-fixed': '#67fbd3',
        outline: '#6d7a73',
        'surface-variant': '#dde4df',
        'inverse-primary': '#5adcb3',
        'secondary-container': '#61f6ea',
        'surface-dim': '#d5dcd7',
        'on-primary-fixed': '#002117',
        'surface-container': '#e9efea',
        tertiary: '#006b56',
        'secondary-fixed': '#65f8ed',
        'secondary-fixed-dim': '#40dcd1',
        'on-surface': '#171d1a',
        'on-primary-fixed-variant': '#00513d',
        'on-secondary-fixed-variant': '#00504b',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#00765f',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'module-gap': '2rem',
        'glass-blur': '24px',
        'internal-padding': '1.5rem',
        'safe-area': '4rem',
      },
      fontFamily: {
        'display-hero': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        metadata: ['Inter', 'sans-serif'],
        'body-large': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-main': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
